import type { Movement, Product, Staff } from "./types";

export const hospital = {
  name: "MedIoT",
  sector: "Almoxarifado de Ferramentas",
  lastSync: "2026-09-24T12:00:00-03:00",
};

export const staff: Staff[] = [
  {
    id: "s1",
    name: "Arthur",
    role: "CEO",
    rfidCard: "67:52:B0:A0",
  },
  {
    id: "s2",
    name: "Enrico",
    role: "Gerente de Operações",
    rfidCard: "77:0C:B2:A0",
  },
  {
    id: "s3",
    name: "Luís Guilherme",
    role: "Técnico em Mecatrônica",
    rfidCard: "97:5D:A3:A0",
  },
  {
    id: "s4",
    name: "Pedro Miguel",
    role: "Auxiliar Administrativo",
    rfidCard: "07:D7:81:A0",
  },
  {
    id: "s5",
    name: "Yago",
    role: "Técnico em Mecatrônica",
    rfidCard: "F7:F4:8F:A0",
  },
];

/** Ferramentas com RFID individual — estoque 1 (item único). */
export const products: Product[] = [
  {
    id: "p1",
    name: "Furadeira elétrica",
    sku: "FUR-ELE",
    category: "Ferramentas",
    unit: "un",
    stock: 1,
    minStock: 1,
    criticalStock: 0,
    rfidTag: "F5:76:82:B1",
  },
  {
    id: "p2",
    name: "Parafusadeira",
    sku: "PAR-ELE",
    category: "Ferramentas",
    unit: "un",
    stock: 1,
    minStock: 1,
    criticalStock: 0,
    rfidTag: "47:5F:A1:A0",
  },
  {
    id: "p3",
    name: "Multímetro digital",
    sku: "MUL-DIG",
    category: "Instrumentos",
    unit: "un",
    stock: 1,
    minStock: 1,
    criticalStock: 0,
    rfidTag: "B7:9B:AC:A0",
  },
  {
    id: "p4",
    name: "Alicate amperímetro",
    sku: "ALI-AMP",
    category: "Instrumentos",
    unit: "un",
    stock: 1,
    minStock: 1,
    criticalStock: 0,
    rfidTag: "A7:5F:BB:A0",
  },
  {
    id: "p5",
    name: "Caixa de ferramentas",
    sku: "CAI-FER",
    category: "Ferramentas",
    unit: "un",
    stock: 1,
    minStock: 1,
    criticalStock: 0,
    rfidTag: "D7:23:9F:A0",
  },
  {
    id: "p6",
    name: "Extensão elétrica 20m",
    sku: "EXT-20M",
    category: "Elétrica",
    unit: "un",
    stock: 1,
    minStock: 1,
    criticalStock: 0,
    rfidTag: "87:44:8E:A0",
  },
];

/**
 * Histórico demo (saídas/devoluções RFID).
 * Estado final: todos os itens em estoque (stock 1).
 */
export const movements: Movement[] = [
  {
    id: "m1",
    productId: "p1",
    staffId: "s3",
    type: "saida",
    quantity: 1,
    timestamp: "2026-09-22T10:15:00-03:00",
    source: "rfid",
  },
  {
    id: "m2",
    productId: "p1",
    staffId: "s3",
    type: "entrada",
    quantity: 1,
    timestamp: "2026-09-22T16:40:00-03:00",
    source: "rfid",
  },
  {
    id: "m3",
    productId: "p2",
    staffId: "s5",
    type: "saida",
    quantity: 1,
    timestamp: "2026-09-23T09:20:00-03:00",
    source: "rfid",
  },
  {
    id: "m4",
    productId: "p2",
    staffId: "s5",
    type: "entrada",
    quantity: 1,
    timestamp: "2026-09-23T17:05:00-03:00",
    source: "rfid",
  },
  {
    id: "m5",
    productId: "p3",
    staffId: "s2",
    type: "saida",
    quantity: 1,
    timestamp: "2026-09-23T11:00:00-03:00",
    source: "rfid",
  },
  {
    id: "m6",
    productId: "p3",
    staffId: "s2",
    type: "entrada",
    quantity: 1,
    timestamp: "2026-09-23T15:30:00-03:00",
    source: "rfid",
  },
  {
    id: "m7",
    productId: "p6",
    staffId: "s4",
    type: "saida",
    quantity: 1,
    timestamp: "2026-09-24T08:45:00-03:00",
    source: "rfid",
  },
  {
    id: "m8",
    productId: "p6",
    staffId: "s4",
    type: "entrada",
    quantity: 1,
    timestamp: "2026-09-24T12:10:00-03:00",
    source: "rfid",
  },
  {
    id: "m9",
    productId: "p5",
    staffId: "s1",
    type: "saida",
    quantity: 1,
    timestamp: "2026-09-21T14:00:00-03:00",
    source: "rfid",
  },
  {
    id: "m10",
    productId: "p5",
    staffId: "s1",
    type: "entrada",
    quantity: 1,
    timestamp: "2026-09-21T18:20:00-03:00",
    source: "rfid",
  },
  {
    id: "m11",
    productId: "p4",
    staffId: "s3",
    type: "saida",
    quantity: 1,
    timestamp: "2026-09-20T10:30:00-03:00",
    source: "rfid",
  },
  {
    id: "m12",
    productId: "p4",
    staffId: "s3",
    type: "entrada",
    quantity: 1,
    timestamp: "2026-09-20T16:00:00-03:00",
    source: "rfid",
  },
];
